with-expecter: true
packages:
  github.com/wstool/wst/app:
    config:
      dir: mocks/generated/app
    interfaces:
      Command: {}
      Foundation: {}
      File: {}
      Fs: {}
      HttpClient: {}
      VegetaAttacker: {}
      VegetaMetrics: {}
  github.com/wstool/wst/conf:
    config:
      dir: mocks/generated/conf
    interfaces:
      Maker: {}
  github.com/wstool/wst/conf/loader:
    config:
      dir: mocks/generated/conf/loader
    interfaces:
      LoadedConfig: {}
      Loader: {}
  github.com/wstool/wst/conf/merger:
    config:
      dir: mocks/generated/conf/merger
    interfaces:
      Merger: {}
  github.com/wstool/wst/conf/overwrites:
    config:
      dir: mocks/generated/conf/overwrites
    interfaces:
      Overwriter: {}
  github.com/wstool/wst/conf/parser:
    config:
      dir: mocks/generated/conf/parser
    interfaces:
      Parser: {}
  github.com/wstool/wst/conf/parser/factory:
    config:
      dir: mocks/generated/conf/parser/factory
    interfaces:
      Functions: {}
  github.com/wstool/wst/run/actions:
    config:
      dir: mocks/generated/run/actions
    interfaces:
      ActionMaker: {}
  github.com/wstool/wst/run/actions/action:
    config:
      dir: mocks/generated/run/actions/action
    interfaces:
      Action: {}
      Maker: {}
  github.com/wstool/wst/run/actions/action/bench:
    config:
      dir: mocks/generated/run/actions/action/bench
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/command:
    config:
      dir: mocks/generated/run/actions/action/command
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/expect:
    config:
      dir: mocks/generated/run/actions/action/expect
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/not:
    config:
      dir: mocks/generated/run/actions/action/not
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/parallel:
    config:
      dir: mocks/generated/run/actions/action/parallel
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/reload:
    config:
      dir: mocks/generated/run/actions/action/reload
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/request:
    config:
      dir: mocks/generated/run/actions/action/request
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/restart:
    config:
      dir: mocks/generated/run/actions/action/restart
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/sequential:
    config:
      dir: mocks/generated/run/actions/action/sequential
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/start:
    config:
      dir: mocks/generated/run/actions/action/start
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/actions/action/stop:
    config:
      dir: mocks/generated/run/actions/action/stop
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/environments:
    config:
      dir: mocks/generated/run/environments
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/environments/environment:
    config:
      dir: mocks/generated/run/environments/environment
    interfaces:
      Environment: {}

  github.com/wstool/wst/run/environments/environment/output:
    config:
      dir: mocks/generated/run/environments/environment/output
    interfaces:
      Collector: {}
      Maker: {}
  github.com/wstool/wst/run/environments/environment/providers/docker:
    config:
      dir: mocks/generated/run/environments/environment/providers/docker
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/environments/environment/providers/docker/client:
    config:
      dir: mocks/generated/run/environments/environment/providers/docker/client
    interfaces:
      Client: {}
      Maker: {}
  github.com/wstool/wst/run/environments/environment/providers/kubernetes:
    config:
      dir: mocks/generated/run/environments/environment/providers/kubernetes
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/environments/environment/providers/kubernetes/clients:
    config:
      dir: mocks/generated/run/environments/environment/providers/kubernetes/clients
    interfaces:
      ConfigMapClient: {}
      DeploymentClient: {}
      PodClient: {}
      ServiceClient: {}
      Maker: {}
  github.com/wstool/wst/run/environments/environment/providers/local:
    config:
      dir: mocks/generated/run/environments/environment/providers/local
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/environments/task:
    config:
      dir: mocks/generated/run/environments/task
    interfaces:
      Task: {}
  github.com/wstool/wst/run/expectations:
    config:
      dir: mocks/generated/run/expectations
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/instances:
    config:
      dir: mocks/generated/run/instances
    interfaces:
      Instance: { }
      InstanceMaker: { }
  github.com/wstool/wst/run/instances/runtime:
    config:
      dir: mocks/generated/run/instances/runtime
    interfaces:
      Data: {}
      Maker: {}
  github.com/wstool/wst/run/metrics:
    config:
      dir: mocks/generated/run/metrics
    interfaces:
      Metric: {}
      Metrics: {}
  github.com/wstool/wst/run/parameters:
    config:
      dir: mocks/generated/run/parameters
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/parameters/parameter:
    config:
      dir: mocks/generated/run/parameters/parameter
    interfaces:
      Maker: {}
      Parameter: {}
  github.com/wstool/wst/run/resources/scripts:
    config:
      dir: mocks/generated/run/resources/scripts
    interfaces:
      Maker: {}
      Script: {}
  github.com/wstool/wst/run/sandboxes:
    config:
      dir: mocks/generated/run/sandboxes
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/sandboxes/hooks:
    config:
      dir: mocks/generated/run/sandboxes/hooks
    interfaces:
      Hook: {}
      Maker: {}
  github.com/wstool/wst/run/sandboxes/sandbox:
    config:
      dir: mocks/generated/run/sandboxes/sandbox
    interfaces:
      Sandbox: {}
  github.com/wstool/wst/run/sandboxes/sandbox/common:
    config:
      dir: mocks/generated/run/sandboxes/sandbox/common
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/sandboxes/sandbox/container:
    config:
      dir: mocks/generated/run/sandboxes/sandbox/container
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/sandboxes/sandbox/docker:
    config:
      dir: mocks/generated/run/sandboxes/sandbox/docker
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/sandboxes/sandbox/kubernetes:
    config:
      dir: mocks/generated/run/sandboxes/sandbox/kubernetes
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/sandboxes/sandbox/local:
    config:
      dir: mocks/generated/run/sandboxes/sandbox/local
    interfaces:
      Maker: {}
  github.com/wstool/wst/run/servers:
    config:
      dir: mocks/generated/run/servers
    interfaces:
      Maker: {}
      Server: {}
  github.com/wstool/wst/run/servers/actions:
    config:
      dir: mocks/generated/run/servers/actions
    interfaces:
      ExpectAction: {}
      SequentialAction: {}
      Maker: {}
  github.com/wstool/wst/run/servers/configs:
    config:
      dir: mocks/generated/run/servers/configs
    interfaces:
      Config: {}
      Maker: {}
  github.com/wstool/wst/run/servers/templates:
    config:
      dir: mocks/generated/run/servers/templates
    interfaces:
      Maker: {}
      Template: {}
  github.com/wstool/wst/run/services:
    config:
      dir: mocks/generated/run/services
    interfaces:
      Maker: {}
      ServiceLocator: {}
      Service: {}
  github.com/wstool/wst/run/services/template:
    config:
      dir: mocks/generated/run/services/template
    interfaces:
      Maker: {}
      Template: {}
  github.com/wstool/wst/run/services/template/service:
    config:
      dir: mocks/generated/run/services/template/service
    interfaces:
      TemplateService: {}
  github.com/wstool/wst/run/spec:
    config:
      dir: mocks/generated/run/spec
    interfaces:
      Maker: {}
      Spec: {}
  github.com/wstool/wst/run/spec/defaults:
    config:
      dir: mocks/generated/run/spec/defaults
    interfaces:
      Maker: {}
