// Code generated by mockery v2.40.1. DO NOT EDIT.

package app

import (
	afero "github.com/spf13/afero"

	mock "github.com/stretchr/testify/mock"

	zap "go.uber.org/zap"
)

// MockFoundation is an autogenerated mock type for the Foundation type
type MockFoundation struct {
	mock.Mock
}

type MockFoundation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFoundation) EXPECT() *MockFoundation_Expecter {
	return &MockFoundation_Expecter{mock: &_m.Mock}
}

// Fs provides a mock function with given fields:
func (_m *MockFoundation) Fs() afero.Fs {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fs")
	}

	var r0 afero.Fs
	if rf, ok := ret.Get(0).(func() afero.Fs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.Fs)
		}
	}

	return r0
}

// MockFoundation_Fs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fs'
type MockFoundation_Fs_Call struct {
	*mock.Call
}

// Fs is a helper method to define mock.On call
func (_e *MockFoundation_Expecter) Fs() *MockFoundation_Fs_Call {
	return &MockFoundation_Fs_Call{Call: _e.mock.On("Fs")}
}

func (_c *MockFoundation_Fs_Call) Run(run func()) *MockFoundation_Fs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFoundation_Fs_Call) Return(_a0 afero.Fs) *MockFoundation_Fs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFoundation_Fs_Call) RunAndReturn(run func() afero.Fs) *MockFoundation_Fs_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function with given fields:
func (_m *MockFoundation) Logger() *zap.SugaredLogger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *zap.SugaredLogger
	if rf, ok := ret.Get(0).(func() *zap.SugaredLogger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zap.SugaredLogger)
		}
	}

	return r0
}

// MockFoundation_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockFoundation_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockFoundation_Expecter) Logger() *MockFoundation_Logger_Call {
	return &MockFoundation_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockFoundation_Logger_Call) Run(run func()) *MockFoundation_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFoundation_Logger_Call) Return(_a0 *zap.SugaredLogger) *MockFoundation_Logger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFoundation_Logger_Call) RunAndReturn(run func() *zap.SugaredLogger) *MockFoundation_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// LookupEnvVar provides a mock function with given fields: key
func (_m *MockFoundation) LookupEnvVar(key string) (string, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for LookupEnvVar")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (string, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockFoundation_LookupEnvVar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupEnvVar'
type MockFoundation_LookupEnvVar_Call struct {
	*mock.Call
}

// LookupEnvVar is a helper method to define mock.On call
//   - key string
func (_e *MockFoundation_Expecter) LookupEnvVar(key interface{}) *MockFoundation_LookupEnvVar_Call {
	return &MockFoundation_LookupEnvVar_Call{Call: _e.mock.On("LookupEnvVar", key)}
}

func (_c *MockFoundation_LookupEnvVar_Call) Run(run func(key string)) *MockFoundation_LookupEnvVar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFoundation_LookupEnvVar_Call) Return(_a0 string, _a1 bool) *MockFoundation_LookupEnvVar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFoundation_LookupEnvVar_Call) RunAndReturn(run func(string) (string, bool)) *MockFoundation_LookupEnvVar_Call {
	_c.Call.Return(run)
	return _c
}

// UserHomeDir provides a mock function with given fields:
func (_m *MockFoundation) UserHomeDir() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserHomeDir")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFoundation_UserHomeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserHomeDir'
type MockFoundation_UserHomeDir_Call struct {
	*mock.Call
}

// UserHomeDir is a helper method to define mock.On call
func (_e *MockFoundation_Expecter) UserHomeDir() *MockFoundation_UserHomeDir_Call {
	return &MockFoundation_UserHomeDir_Call{Call: _e.mock.On("UserHomeDir")}
}

func (_c *MockFoundation_UserHomeDir_Call) Run(run func()) *MockFoundation_UserHomeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFoundation_UserHomeDir_Call) Return(_a0 string, _a1 error) *MockFoundation_UserHomeDir_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFoundation_UserHomeDir_Call) RunAndReturn(run func() (string, error)) *MockFoundation_UserHomeDir_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFoundation creates a new instance of MockFoundation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFoundation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFoundation {
	mock := &MockFoundation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
